logging:
  level:
    org:
      springframework: INFO
odata:
  jpa:
    punit_name: "com.sap.cloud.cmp.od.service" # used in persistance.xml for Java EE, but in Spring (like here) only used as namespace of the OData service
    request_mapping_path: "open-discovery"
    root_packages: "com.sap.cloud.cmp.od.service"
server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: pgsql@12345
    url: jdbc:postgresql://localhost:5432/compass
    username: postgres
  servlet:
    multipart:
      enabled: false