deployment:
  replicaCount: 1
  image:
    pullPolicy: IfNotPresent
  resources: {}
  resourcesCloudsqlProxy: {}
  resourcesIstioProxy:
    requests: {}
    limits: {}
  args:
    containerPort: 3000
  securityContext: # Set on container level
    runAsUser: 2000
    allowPrivilegeEscalation: false
  strategy: {} # Read more: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
  nodeSelector: {}

database:
  dbPool:
    maxOpenConnections: 30
    maxIdleConnections: 2

authentication:
  allowJWTSigningNone: true
  jwksEndpoint: "http://ory-oathkeeper-api.kyma-system.svc.cluster.local:4456/.well-known/jwks.json"
  identityZone: "id-zone"

server:
  handlerEndpoint: "/v1/callback/{tenantId}"
  tenantPathParam: "tenantId"
