deployment:
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  image:
    pullPolicy: IfNotPresent
  resources: {}
  resourcesCloudsqlProxy: {}
  resourcesIstioProxy:
    requests: {}
    limits: {}
  args:
    containerPort: 3000
  securityContext: # Set on container level
    runAsUser: 2000
    allowPrivilegeEscalation: false
  strategy: {} # Read more: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
  nodeSelector: {}

database:
  dbPool:
    maxOpenConnections: 2
    maxIdleConnections: 1

server:
  handlerEndpoint: "/v1/callback/{tenantId}"
  tenantPathParam: "tenantId"

coverage:
  gatewayHost: compass-tenant-fetcher-coverage
  host: compass-tenant-fetcher-coverage.compass-system.svc.cluster.local
  port: 3001