apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: system-broker-coverage
  namespace: compass-system
  labels:
    release: compass
spec:
  hosts:
    - coverage.kyma.local
  gateways:
    - kyma-system/kyma-gateway
  http:
    - match:
        - uri:
            regex: /.*
      route:
        - destination:
            port:
              number: 5003
            host: system-broker-coverage.compass-system.svc.cluster.local