apiVersion: v1
kind: ConfigMap
metadata:
  name: tracing-overrides
  namespace: kyma-installer
  labels:
    installer: overrides
    component: tracing
    kyma-project.io/installation: ""
data:
  global.tracing.enabled: "true"
  kcproxy.resources.limits.memory: 40Mi
  kcproxy.resources.requests.memory: 10Mi