deployment:
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  image:
    pullPolicy: IfNotPresent
  resources: {}
  args:
    containerPort: 5001
  securityContext: # Set on container level
    runAsUser: 2000
    allowPrivilegeEscalation: false
  allowJWTSigningNone: true # To run integration tests, it has to be enabled
  strategy: {} # Read more: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
  nodeSelector: {}

metrics:
  port: 5002

coverage:
  gatewayHost: compass-system-broker-coverage
  host: compass-system-broker-coverage.compass-system.svc.cluster.local
  port: 5003