apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "fullname" . }}-coverage
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
spec:
  hosts:
    - {{ .Values.coverage.gatewayHost}}.{{ .Values.global.ingress.domainName}}
  gateways:
    - {{ .Values.global.istio.gateway.namespace }}/{{ .Values.global.istio.gateway.name }}
  http:
    - match:
        - uri:
            regex: /.*
      route:
        - destination:
            port:
              number: {{ .Values.coverage.port }}
            host: {{ .Values.coverage.host }}