apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  hosts:
    - '{{ .Values.global.gateway.tls.host }}.cmp-test.dev.kyma.cloud.sap'
  gateways:
    - 'kyma-system/kyma-gateway'
  http:
    - match:
        - uri:
            prefix: /open-discovery
      route:
        - destination:
            host: {{ .Values.global.open_discovery_service.host }}
            port:
              number: {{ .Values.global.open_discovery_service.port }}
      headers:
        request:
          remove:
            {{- range .Values.global.gateway.headers.request.remove }}
            - {{ . }}
      {{- end }}
      corsPolicy:
        allowOrigin:
          - "*"
        allowHeaders:
          - "accept"
          - "content-type"
        allowMethods:
          - "GET"
    - match:
      - uri:
          exact: /od-director
      rewrite:
        uri: /director
      route:
      - destination:
          host: "{{ .Values.global.gateway.tls.host }}.compass-system-skalata.svc.cluster.local"
          port:
            number: {{ .Values.global.director.port }}
      headers:
        request:
          remove:
            {{- range .Values.global.gateway.headers.request.remove }}
            - {{ . }}
            {{- end }}
      corsPolicy:
        allowOrigin:
          - "*"
        allowHeaders:
          - "authorization"
          - "content-type"
          - "tenant"
        allowMethods:
          - "GET"
    - match:
      - uri:
          regex: /.*
      route:
        - destination:
            host: {{ .Values.global.oathkeeper.host }}
            port:
              number: {{ .Values.global.oathkeeper.port }}
      headers:
        request:
          remove:
            {{- range .Values.global.gateway.headers.request.remove }}
            - {{ . }}
            {{- end }}
      corsPolicy:
        allowOrigin:
          - "*"
        allowHeaders:
          - "authorization"
          - "content-type"
          - "tenant"
        allowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"