apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-overrides
  namespace: kyma-installer
  labels:
    installer: overrides
    component: istio
    kyma-project.io/installation: ""
data:
  kyma_istio_operator: |-
    apiVersion: install.istio.io/v1alpha1
    kind: IstioOperator
    metadata:
      namespace: istio-system
    spec:
      addonComponents:
        istiocoredns:
          enabled: true
      components:
        ingressGateways:
        - name: istio-ingressgateway
          k8s:
            hpaSpec:
              maxReplicas: 10
              minReplicas: 3
        egressGateways:
        - name: istio-egressgateway
          enabled: true
      values:
        global:
          podDNSSearchNamespaces:
          - global
          multiCluster:
            enabled: true
          controlPlaneSecurityEnabled: true
        gateways:
          istio-egressgateway:
            env:
              # Needed to route traffic via egress gateway if desired.
              ISTIO_META_REQUESTED_NETWORK_VIEW: "external"      