{{ if .Values.global.images.director.green_version }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: compass-post-migration
  namespace: {{ $.Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: compass-post-migration
  namespace: {{ $.Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: compass-post-migration
subjects:
  - kind: ServiceAccount
    name: compass-post-migration
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: compass-post-migration
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["", "batch", "autoscaling", "apps"]
    resources: ["services", "deployments", "horizontalpodautoscalers", "jobs"]
    verbs: ["get", "update", "patch", "delete"]
---
apiVersion: batch/v1
kind: Job
metadata:
  name: compass-post-migration-job
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 0
  template:
    metadata:
      name: compass-post-migration-job
    spec:
      {{ if .Values.global.isLocalEnv }}
      hostAliases:
        - ip: {{ .Values.global.minikubeIP }}
          hostnames:
            - "{{ .Values.global.gateway.tls.host }}.{{ .Values.global.ingress.domainName }}"
      {{ end }}
      serviceAccountName: compass-post-migration
      restartPolicy: Never
      containers:
        - name: post-migration
          image: "eu.gcr.io/kyma-project/test-infra/alpine-kubectl:v20200617-32c1f3ff"
          command:
            - bash
            - -c
            - |
              function quit_proxy() {
                echo "Sending a quit request for istio-proxy and exiting..."
                curl -XPOST http://127.0.0.1:15020/quitquitquit
                sleep 5
              }

              SUCCESSFUL_MIGRATION_COUNT=$(kubectl get job -n {{ .Release.Namespace }} compass-migration -o json | jq '.status.succeeded')
              # This should not happen because helm will rollback installation if the migrator job fails. Just in case
              if [ $SUCCESSFUL_MIGRATION_COUNT -lt 1 ]
              then
                echo "Migration was not succesful"
                quit_proxy
                exit 1
              fi

              echo "Changing services to forward traffic to new deployments..."
              kubectl get service -n {{ .Release.Namespace }}  compass-director -o json \
                | jq '.spec.selector.version = "{{ .Values.global.images.director.green_version | lower }}"' \
                | kubectl replace -f -

              if [ $? -ne 0 ]
              then
                echo "Service could not be changed to forward to new deployments"
                quit_proxy
                exit 1
              fi

              echo "Deleting old horizonal-pod-autoscaler..."
              kubectl delete horizontalpodautoscaler -n {{ .Release.Namespace }} compass-director-{{ .Values.global.images.director.version | lower }}

              echo "Deleting old deployment..."
              kubectl delete deployment -n {{ .Release.Namespace }} compass-director-{{ .Values.global.images.director.version | lower }}

              echo "Post migration job finished"
              quit_proxy
              exit 0
{{ end }}
