{{ if gt (len .Values.global.images.director.versions) 1 }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: compass-post-migration
  namespace: {{ $.Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: compass-post-migration
  namespace: {{ $.Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: compass-post-migration
subjects:
  - kind: ServiceAccount
    name: compass-post-migration
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: compass-post-migration
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["", "batch", "autoscaling"]
    resources: ["services", "deployments", "horizontalpodautoscalers", "jobs"]
    verbs: ["get", "update", "patch", "delete"]
---
apiVersion: batch/v1
kind: Job
metadata:
  name: compass-post-migration-job
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 0
  template:
    metadata:
      name: compass-post-migration-job
    spec:
      {{ if .Values.global.isLocalEnv }}
      hostAliases:
        - ip: {{ .Values.global.minikubeIP }}
          hostnames:
            - "{{ .Values.global.gateway.tls.host }}.{{ .Values.global.ingress.domainName }}"
      {{ end }}
      serviceAccountName: compass-post-migration
      restartPolicy: Never
      containers:
        - name: post-migration
          image: "eu.gcr.io/kyma-project/test-infra/alpine-kubectl:v20200617-32c1f3ff"
          command:
            - bash
            - -c
            - |
              SUCCESSFUL_MIGRATION_COUNT=$(kubectl get job -n compass-system compass-migration -o json | jq '.status.succeeded')
              kubectl get hpa -n compass-system compass-director-{{ (first .Values.global.images.director.versions) | lower }} -o json
              kubectl get service -n compass-system compass-director -o json
{{ end }}
