{{ $outerScope := . }}
{{ $version_list := list .Values.global.images.director.version }}
{{ if .Values.global.images.director.green_version }}
{{ $version_list = append $version_list .Values.global.images.director.green_version }}
{{ end }}
{{- range $version_list }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "fullname" $outerScope }}-{{ (lower .) }}
  namespace: {{ $.Release.Namespace }}
spec:
  minReplicas: {{ $.Values.deployment.minReplicas }}
  maxReplicas: {{ $.Values.deployment.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "fullname" $outerScope }}-{{ (lower .) }}
  targetCPUUtilizationPercentage: {{ $.Values.deployment.targetCPUUtilizationPercentage }}
---
{{ end }}