apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ template "name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  hosts:
    - connector.{{ .Values.global.ingress.domainName }}
  gateways:
    - {{ .Values.global.istio.gateway.namespace }}/{{ .Values.global.istio.gateway.name }}
  http:
      - match:
        - uri:
            exact: /healthz
        route:
          - destination:
              port:
                number: {{ .Values.global.connector.graphql.external.port }}
              host: {{ template "fullname" . }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "fullname" . }}-coverage
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
spec:
  hosts:
    - {{ .Values.coverage.gatewayHost}}.{{ .Values.global.ingress.domainName}}
  gateways:
    - {{ .Values.global.istio.gateway.namespace }}/{{ .Values.global.istio.gateway.name }}
  http:
    - match:
        - uri:
            regex: /.*
      route:
        - destination:
            port:
              number: {{ .Values.coverage.port }}
            host: {{ .Values.coverage.host }}