apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: apisalesdemo2.successfactors.eu
  namespace: default
spec:
  hosts:
    - apisalesdemo2.successfactors.eu
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: TLS
  resolution: DNS