apiVersion: v1
kind: Service
metadata:
  name: audit-log-service
  namespace: default
spec:
  selector:
    none: does-not-exist
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 443
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: audit-log-service-se
  namespace: default
spec:
  hosts:
  - api.auditlog.cf.sap.hana.ondemand.com
  location: MESH_EXTERNAL
  ports:
  - name: https
    number: 443
    protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: audit-log-service-vs
  namespace: default
spec:
  hosts:
  - audit-log-service.default.svc.cluster.local
  http:
  - match:
    - port: 80
    rewrite:
        authority: api.auditlog.cf.sap.hana.ondemand.com
    route:
    - destination:
        host: api.auditlog.cf.sap.hana.ondemand.com
        subset: tls-origination
        port:
          number: 443
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: audit-log-service-dr
  namespace: default
spec:
  host: api.auditlog.cf.sap.hana.ondemand.com
  subsets:
  - name: tls-origination
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: SIMPLE
