apiVersion: v1
kind: Service
metadata:
  name: sales-data
  namespace: default
  labels:
    app: admiral-watcher
spec:
  selector:
    app: connectivity-proxy
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 20003
