apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: clm-sl-ans-live-ans-service-api.cfapps.eu10.hana.ondemand.com
  namespace: default
spec:
  hosts:
    - clm-sl-ans-live-ans-service-api.cfapps.eu10.hana.ondemand.com
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: TLS
  resolution: DNS
