apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: default.xs01.global
  namespace: default
spec:
  hosts:
    - jdbc.localhost
  ports:
    - name: http
      number: 5432
      protocol: tcp
  location: MESH_EXTERNAL
  resolution: DNS