deployment:
  port: 8080
  image:
    pullPolicy: IfNotPresent
  resources: {}
  securityContext: # Set on container level
    runAsUser: 2000
    allowPrivilegeEscalation: false

service:
  port: 8080

coverage:
  gatewayHost: compass-external-services-mock-coverage
  host: compass-external-services-mock-coverage.compass-system.svc.cluster.local
  port: 8081
